/** Stable API codes — mirror services/dff-service model constants. */
export const MODEL_ERROR_CODE = {
  NOT_FOUND: "MODEL_NOT_FOUND",
  ARCHIVED: "MODEL_ARCHIVED",
  DELETED: "MODEL_DELETED",
  READONLY: "MODEL_READONLY",
  NOT_ACTIVE: "MODEL_NOT_ACTIVE",
  SLUG_EXISTS: "MODEL_SLUG_EXISTS",
  NAME_EXISTS: "MODEL_NAME_EXISTS",
  DRUG_NOT_FOUND: "MODEL_DRUG_NOT_FOUND",
  DRUG_INVALID: "MODEL_DRUG_INVALID",
  FACTOR_SET_DUPLICATE: "MODEL_FACTOR_SET_DUPLICATE",
  VERSION_CONFLICT: "MODEL_VERSION_CONFLICT",
  INVALID_STATUS_TRANSITION: "MODEL_INVALID_STATUS_TRANSITION",
} as const;

/** Matches backend `MODEL_LIMITS.MAX_FACTOR_SETS`. */
export const MODEL_MAX_FACTOR_SETS = 50;
